import type { Metadata } from "next";
import "./globals.css";
import {NextIntlClientProvider, hasLocale} from 'next-intl';
import { getMessages } from 'next-intl/server';
import {notFound} from 'next/navigation';
import {routing} from '@/i18n/routing';
import Header from '@/components/Header';
import Footer from "@/components/Footer";
import DrawerMenu from "@/components/DrawerMenu";
import FloatingActionGroup from "@/components/FloatingActionGroup";

export const metadata: Metadata = {
  title: "FCLOGO",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params
}: {
  children: React.ReactNode
  params: Promise<{locale: string}>
}) {
  const {locale} = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  const messages = await getMessages();
  return (
    <html lang={locale} data-theme="light">
      <body className="antialiased">
        <NextIntlClientProvider locale={locale} messages={messages}>
          <div className="drawer">
            <input id="main-drawer" type="checkbox" className="drawer-toggle" />
            <div className="drawer-content flex flex-col bg-base-300 min-h-screen">
              <Header />
              {children}
              <Footer />
              <FloatingActionGroup />
            </div>
            <DrawerMenu />
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
